### PR TITLE
Added homepage changes and refactored components into their own view …

### PR DESCRIPTION
**Pull request by janetcl**
Screenshot 2023-02-25 at 5 14 39 PM

Here's the Figma to compare: 

Screenshot 2023-02-25 at 5 15 48 PM

Verified it builds and works on my local machine. The colors are still not perfect but are easy to fix later.

### CODE REVIEW

**Comment by janetcl** [comment]
This is the most up to date UI: 
Screenshot 2023-02-25 at 5 28 01 PM

**Comment by janetcl** [comment]
UI Update: 
MicrosoftTeams-image

**Comment by kirstyihen** [comment]
LGTM

**Review by kirstyihen — APPROVED** [review]
LGTM

**Pull request merged**
